-
  branches:
    only:
      - master

  configuration: Release
  deploy:
    release: myproduct-v(0.0.0)
    #description: 'Release description'
    provider: GitHub
    auth_token:
      secure: 9e383e9c486efe9a7802cc88ce153b439d94ab99 # your encrypted token from GitHub
    artifact: MindKeeper\Installer\MindKeeperInstall.zip            # upload all NuGet packages to release assets
    draft: false
    prerelease: false
    on:
      branch: master                 # release from master branch only
      appveyor_repo_tag: true        # deploy on tag push only
-
  configuration: Debug