# configuration for "master" branch
# build in Release mode and deploy to Azure
-
  branches:
    only:
      - master

  configuration: Release
  #deploy:
    #release: myproduct-v(0.0.0)
    ##description: 'Release description'
    #provider: GitHub
    #auth_token:
      #secure: bade7d72b3f0eb9b9dd82475206f1a41a0c14a6a # your encrypted token from GitHub
    #artifact: MindKeeper\Installer\MindKeeperInstall.zip            # upload all NuGet packages to release assets
    #draft: false
    #prerelease: false
    #on:
      #branch: master                 # release from master branch only
      #appveyor_repo_tag: true        # deploy on tag push only

# "fall back" configuration for all other branches
# no "branches" section defined
# do not deploy at all
-
  configuration: Debug