version: 0.0.0.{build}
pull_requests:
  do_not_increment_build_number: true
configuration: Release
before_build:
- ps: "nuget restore MindKeeper\\MindKeeper.sln\n\n$contentAssembly = Get-Content MindKeeper\\SharedAssemblyInfo.cs\n\"'\"+$contentAssembly+\"'\" -match '\\[assembly: AssemblyVersion\\(\\\"(?<major>\\d+).(?<minor>\\d+).(?<patch>\\d+).(\\*)\\\"\\)\\]'\n$matchVar = $matches\n$versionNew = \"{0}.{1}.{2}\" -f $matchVar[\"major\"],$matchVar[\"minor\"],$matchVar[\"patch\"]\n\n\n$contentInstaller = Get-Content MindKeeper\\Installer\\MKInstaller.iss\n\"'\"+$contentInstaller+\"'\" -match '\\#define MyAppVersion \\\"(?<major>\\d+).(?<minor>\\d+).(?<patch>\\d+)\\\"'\n$matchVar1 = $matches\n$versionOld = \"{0}.{1}.{2}\" -f $matchVar1[\"major\"],$matchVar1[\"minor\"],$matchVar1[\"patch\"]\n\n\n(Get-Content MindKeeper\\Installer\\MKInstaller.iss) | \nForeach-Object {$_ -replace $versionOld,$versionNew}  | \nOut-File -Encoding UTF8 MindKeeper\\Installer\\MKInstaller.iss\n\n$contentCI = Get-Content appveyor.yml\n\"'\"+$contentCI+\"'\" -match 'release: MK-v(?<major>\\d+).(?<minor>\\d+).(?<patch>\\d+)'\n$matchVar2 = $matches\n$versionOldCI = \"{0}.{1}.{2}\" -f $matchVar2[\"major\"],$matchVar2[\"minor\"],$matchVar2[\"patch\"]\n\n(Get-Content appveyor.yml) | \nForeach-Object {$_ -replace $versionOldCI,$versionNew} | \nOut-File -Encoding UTF8 appvyor.yml\n\nGet-Content appveyor.yml\n\necho $versionOldCI\n\necho $versionNew"
build:
  parallel: true
  verbosity: minimal
after_build:
- cmd: MindKeeper\packages\Tools.InnoSetup.5.5.6\tools\iscc "MindKeeper\Installer\MKInstaller.iss"
artifacts:
- path: MindKeeper\Installer\MindKeeperInstall\
deploy:
- provider: GitHub
  release: MK-v0.0.0
  auth_token:
    secure: dxXnDldxYhUSIpOtmipHvoDe77ApzWSAgwlaxo0QWlA5ACBgb2OJNSLyFFTIIQGP
  on:
    branch: master
    configuration: Release
    appveyor_repo_tag: true