branches:
  only:
    - master	
  configuration: Release
  
  #configuration: Debug

before_build:
	- ps: nuget restore MindKeeper\MindKeeper.sln
	
	- ps: $contentAssembly = Get-Content MindKeeper\SharedAssemblyInfo.cs "'"+$contentAssembly+"'" -match '\[assembly: AssemblyVersion\(\"(?<major>\d+).(?<minor>\d+).(?<patch>\d+).(\*)\"\)\]' $matchVar = $matches $versionNew = "{0}.{1}.{2}" -f $matchVar["major"],$matchVar["minor"],$matchVar["patch"]
	
	- ps: $contentInstaller = Get-Content MindKeeper\Installer\MKInstaller.iss "'"+$contentInstaller+"'" -match '\#define MyAppVersion \"(?<major>\d+).(?<minor>\d+).(?<patch>\d+)\"' $matchVar1 = $matches $versionOld = "{0}.{1}.{2}" -f $matchVar1["major"],$matchVar1["minor"],$matchVar1["patch"]	
	
	- ps: (Get-Content MindKeeper\Installer\MKInstaller.iss) | Foreach-Object {$_ -replace $versionOld,$versionNew}  | Out-File -Encoding UTF8 MindKeeper\Installer\MKInstaller.iss

after_build:
	- ps: MindKeeper\packages\Tools.InnoSetup.5.5.6\tools\iscc "MindKeeper\Installer\MKInstaller.iss"

artifacts:

  # pushing a single file
  - path: MindKeeper/Installer/MindKeeperInstall.zip

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

# providers: Local, FTP, WebDeploy, AzureCS, AzureBlob, S3, NuGet, Environment
# provider names are case-sensitive!
deploy:

    # Deploy to GitHub Releases
  - provider: GitHub
    artifact: MindKeeper/Installer/MindKeeperInstall.zip          # upload all NuGet packages to release assets
    draft: false
    prerelease: false
    on:
      branch: master                # release from master branch only
      appveyor_repo_tag: true       # deploy on tag push only