before_build:
nuget restore MindKeeper\MindKeeper.sln
$contentAssembly = Get-Content MindKeeper\SharedAssemblyInfo.cs
"'"+$contentAssembly+"'" -match '\[assembly: AssemblyVersion\(\"(?<major>\d+).(?<minor>\d+).(?<patch>\d+).(\*)\"\)\]'
$matchVar = $matches
$versionNew = "{0}.{1}.{2}" -f $matchVar["major"],$matchVar["minor"],$matchVar["patch"]
$contentInstaller = Get-Content MindKeeper\Installer\MKInstaller.iss
"'"+$contentInstaller+"'" -match '\#define MyAppVersion \"(?<major>\d+).(?<minor>\d+).(?<patch>\d+)\"'
$matchVar1 = $matches
$versionOld = "{0}.{1}.{2}" -f $matchVar1["major"],$matchVar1["minor"],$matchVar1["patch"]
(Get-Content MindKeeper\Installer\MKInstaller.iss) | 
Foreach-Object {$_ -replace $versionOld,$versionNew}  | 
Out-File -Encoding UTF8 MindKeeper\Installer\MKInstaller.iss


after_build:
cd
MindKeeper\packages\Tools.InnoSetup.5.5.6\tools\iscc "MindKeeper\Installer\MKInstaller.iss"
-
  branches:
    only:
      - master

  configuration: Release
  deploy:
    release: myproduct-v(0.0.0)
    #description: 'Release description'
    provider: GitHub
    auth_token:
      secure: bade7d72b3f0eb9b9dd82475206f1a41a0c14a6a # your encrypted token from GitHub
    artifact: MindKeeper\Installer\MindKeeperInstall.zip            # upload all NuGet packages to release assets
    draft: false
    prerelease: false
    on:
      branch: master                 # release from master branch only
      appveyor_repo_tag: true        # deploy on tag push only
	  
	  
# "fall back" configuration for all other branches
# no "branches" section defined
# do not deploy at all
-
  configuration: Debug